version: '3.9'
services:
  db:
    container_name: db
    image: postgres:16.3
    restart: always
    ports:
      - $DATABASE_PORT:5432
    environment:
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASS
      - POSTGRES_DB=$DATABASE_NAME
